### ISSUE TITLE
'Request' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by visibleajay** [soroushchehresa/axios-react#4]
Receiving `'Request' cannot be used as a JSX component.` on as mentioned with DemoCode.

Any Hints on resolving this. Using it in a `.tsx` file.

**Comment by soroushchehresa** [comment]
@visibleajay Thank you for this report.
This issue fixed on [v2.0.7](https://github.com/soroushchehresa/axios-react/releases/tag/v2.0.7).
